apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-prod
  namespace: argocd
spec:
  destination:
    namespace: prometheus-node-exporter
    name: kind
  project: default
  sources:
    # Chart from Chart Repo
    - chart: prometheus-node-exporter
      repoURL: https://github.com/prometheus-community/helm-charts/
      targetRevision: 0.1.0
      helm:
        valueFiles:
        - $values/application/values-app1.yaml
    # Values from Git
    - repoURL: 'https://github.com/kingsleyzikora/demo-dev.git'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true